config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items, only: [:index, :show, :create, :new, :edit, :update, :destroy] do
    resources :bookings
  end

    get "profile", to: "profiles#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
 class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_many :bookings
  has_many :users, through: :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  mount_uploader :photo, PhotoUploader


  validates :title, presence: true
  validates :description, presence: true
  validates :photo, presence: true
  validates :price, presence: true
  # validates :availability, presence: true -- uncomment this when we work without seed, marisa.

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, foreign_key: "owner_id", dependent: :destroy
  has_many :bookings
  has_one :profile
  after_save :create_profile

  mount_uploader :photo, PhotoUploader

  validates :email, uniqueness: true, presence: true


  def create_profile
    profile = Profile.new
    profile.user = self
    profile.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :find_user, except: [:destroy]

  def new
    @booking = Booking.new
    authorize @booking
    @item = Item.find(params[:item_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.item = Item.find(params[:item_id])
    authorize @booking
    if @booking.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to booking_index_path
  end

  private

  def find_user
    @user = current_user
  end

  def booking_params
    params.require(:booking).permit(:user_id, :item_id, :start_date, :end_date)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:search].present?
      sql_query = "address ILIKE :query"
      @items = policy_scope(Item.where(sql_query, query: "%#{params[:search]}%"))
    else
      @items = policy_scope(Item.where.not(latitude: nil, longitude: nil))
    end

    @markers = @items.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { item: item }),
        image_url: helpers.asset_url('surf.png')
      }
    end
  end

  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
    authorize @item
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    authorize @item
    @item.owner = current_user

    if @item.save
      redirect_to items_path, notice: 'Item has been created'
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def update
    @item = Item.find(params[:id])
    authorize @item
    if @item.update(item_params)
    redirect_to item_path(@item), notice: 'Item has been edited'
  else
    render :edit
  end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    authorize @item
    redirect_to items_path, notice: 'Item has been deleted'
  end

  private

  def item_params
    params.require(:item).permit(:title, :photo, :price, :availability, :description, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
def dashboard
  @user = current_user
  @owned_items = policy_scope(Item).where(owner: current_user)
  @booked_items = policy_scope(Item).select do |item|
    item.users.include?(current_user)
  end
  if @user.profile
  @profile = current_user.profile
  else
  @profile = Profile.create(user: @user)
  end
  authorize @profile

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container text-center page-wrapper">

<div class='row justify-content-center'>
<div class="col-xs-12 col-sm-6 col-md-4">
<h1>You have booked your <%= @item.title %> ! 🎉 </h1>
 <%= cl_image_tag(@item.photo, class: "show_photo") %>
    <br>
    <h4 class="mt-10"><%= @item.description %></h4>
    <br>
<%= link_to profile_path do %>
<button type="button" class="profile_button btn btn-outline-dark ">Go to profile
</button>
<% end %>
</div>
</div>
</div>

app/views/items/_infowindow.html.erb
<%= item.title %>

app/views/items/edit.html.erb
<div class="container">
  <h1 align="center">Edit your item</h1>
  <div class="form-inputs">
    <%= simple_form_for @item do |f| %>
      <%= f.input :title %>
      <%= f.input :price %>
      <%= f.input :availability %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden  %>
      <%= f.submit "Edit Item", class: 'form-actions btn btn-outline-dark btn-sm submit_button submit-form-button btn btn btn-lg btn-block' %>
    </button>
  <% end %>
</div>
</div>
</div >

app/views/items/index.html.erb
<% if params[:search].present? %>
  <h1 style="margin-left: 100px;">Items for Rent in <%= params[:search].capitalize %></h1>
<% else %>
  <h1 style="margin-left: 100px;">Items for Rent</h1>
<% end %>
<div class="main-container">
  <div class="cards">
    <% @items.each do |item|  %>
      <div class="card">
        <%= link_to item_path(item) do  %>
          <%= cl_image_tag(item.photo, class: "item_photo") %>
          <h4><%= item.title %></h4>
          <p><%= truncate item.description, length: 100 %></p>
          <p class="price">€<%= item.price %></p>
        <% end %>
      </div>
    <% end %>
  </div>
  <div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1 align="center">List your item</h1>
  <div class="form-inputs">
    <%= simple_form_for @item do |f| %>
      <%= f.input :title %>
      <%= f.input :price %>
      <%= f.input :availability %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden  %>
      <%= f.submit "Create Item", class: ' form-actions btn btn-outline-dark btn-sm submit_button submit-form-button btn btn btn-lg btn-block button' %>
    </button>
  <% end %>
</div>
</div>
</div >

app/views/items/show.html.erb
<% if policy(Item).show? %>

<%= cl_image_tag(@item.photo, class: "jumbotron-show") %>
<div class="container margin-top-negative">
  <br>
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <div class="flex-tile">
          <h4><%= @item.title %></h4>
          <h4 class="price-show">€<%= @item.price %></h4></h4>

        </div>
        <p><%= @item.address %></p>
      </div>
      <div class="flat-show-card">
        <p><%= @item.description %></p>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-card">
        <h4>Book this item!</h4>
        <%= simple_form_for [@item, @booking] do |f| %>
          <%= f.input :start_date, as: :string, required: true, input_html: {id: "start_date"} %>
          <%= f.input :end_date, as: :string, required: true, input_html: {id: "end_date"} %>
          <div align="center">
            <%= f.submit class: "btn btn-outline-dark my-2 my-sm-0"%>
          </div>
        <% end %>
        <div class="edit-delete mt-2">
          <div class="edit-font">
            <% if policy(@item).edit? %>
              <%= link_to "Edit", edit_item_path(@item.id) %>
            <% end %>
          </div>
          <div class="delete-font">
            <% if policy(@item).destroy? %>
              <%= link_to "Delete", item_path(@item.id), method: 'delete' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BorrowBuddy</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <% if content_for? :nav %>
      <%= content_for :nav %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <div class="page-wrapper">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for :nav, render('shared/navbar_home') %>
<div class="jumbotron" id="hero">
  <div class="container">
    <h1 class="display-3">Borrow what you need</h1>
    <p>A new way to borrow the things you need, when you need them. Leave your suitcase at home!</p>
    <!--     <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Enter a city" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <%= form_tag(items_path, method: 'get', class: "form-inline") do %>
      <%= search_field_tag :search, params[:search], placeholder: "Enter a city", class: "form-control mr-sm-2" %>
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    <% end %>
  </div>
</div>
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4 steps">
      <%= image_tag("golden-gate.png", class: "icon") %>
      <h2>Choose a City & Category</h2>
    </div>
    <div class="col-md-4 steps">
      <%= image_tag("bicycle.png", class: "icon") %>
      <h2>Find the Equipment you Need</h2>
    </div>
    <div class="col-md-4 steps">
      <%= image_tag("goal.png", class: "icon") %>
      <h2>Pick up Locally and Have Fun!</h2>
    </div>
  </div>
  <hr>
</div>

app/views/profiles/dashboard.html.erb
<div class = "container" >
  <div class = "profile-card text-align">
    <h1>My profile</h1>
    <p><%= @user.email %></p>
    <p><%=  @user.username %></p>
    <%= cl_image_tag @user.photo, class: "profile-pic" %>
  </div>

  <div class="d-flex justify-content-between">

    <div class = "card-products mr-5">
      <h2>My listing</h2>
      <div class="row">
        <% @owned_items.each do |item| %>
        <div class="col-xs-12 col-sm-6">
        <div class="card card-dashboard">
          <%= link_to item_path(item) do  %>
            <%= cl_image_tag(item.photo, class: "card-dashboard-photo") %>
            <h4><%= item.title %></h4>
            <p><%= truncate item.description, length: 100 %></p>
            <p class="price">€<%= item.price %></p>
          <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div class = "card-products ml-5">
      <h2>My bookings</h2>
      <div class="row">
        <% @booked_items.each do |item| %>
        <div class="col-xs-12 col-sm-6">
        <div class="card card-dashboard">
          <%= link_to item_path(item) do  %>
            <%= cl_image_tag(item.photo, class: "card-dashboard-photo") %>
            <h4><%= item.title %></h4>
            <p><%= truncate item.description, length: 100 %></p>
            <p class="price">€<%= item.price %></p>
          <% end %>
          </div>
        </div>
        <% end %>
      </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Made with <i class="fas fa-skiing"></i> at Le Wagon Lisbon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "surf_icon.png" %> BorrowBuddy
  <% end %>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <%= form_tag(items_path, method: 'get', class: "form-inline search-nav") do %>
    <%= search_field_tag :search, params[:search], placeholder: "Enter a city", class: "form-control mr-sm-2" %>
    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Listing", new_item_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "surf_icon.png" %> BorrowBuddy
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Listing", new_item_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>